In [ ]:
# Aggregation operations, Axis-wise operations, Concat, stacking, splitting
# matrix multiplication

In [1]:
import numpy as np

# Aggregation operations

In [3]:
arr1 = np.random.randint(10, 100, (3, 5))
arr2 = np.random.randint(10, 100, (3, 5))

In [4]:
arr1

array([[86, 95, 12, 49, 87],
       [79, 51, 13, 63, 82],
       [37, 45, 70, 35, 13]])

In [5]:
arr2

array([[22, 54, 20, 64, 57],
       [52, 25, 42, 51, 91],
       [62, 28, 47, 26, 71]])

In [6]:
arr1.sum()

817

In [7]:
arr1.mean()

54.46666666666667

In [8]:
round(arr1.mean(), 2)

54.47

In [9]:
arr1.min()

12

In [10]:
arr1.max()

95

In [11]:
# How far the datapoints are distributed from the center(mean)
arr1.std()

27.60161025898469

In [12]:
# Squared distance between datapoints and the center(mean)
arr1.var()

761.8488888888888

# Axis-wise operations

In [13]:
arr1

array([[86, 95, 12, 49, 87],
       [79, 51, 13, 63, 82],
       [37, 45, 70, 35, 13]])

In [16]:
arr1.sum(axis = 0) # axis 0 means columns and 1 means row

array([202, 191,  95, 147, 182])

In [17]:
arr1.sum(axis = 1) # axis 0 means columns and 1 means row

array([329, 288, 200])

In [18]:
arr1.mean(axis = 1)

array([65.8, 57.6, 40. ])

In [19]:
arr1.min(axis = 1)

array([12, 13, 13])

In [20]:
arr1[0].sum()

329

In [21]:
arr1[:, 0].sum()

202

# Concat, stacking, splitting

In [22]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])

In [23]:
a

array([[1, 2],
       [3, 4]])

In [25]:
a.shape

(2, 2)

In [24]:
b

array([[5, 6]])

In [26]:
b.shape

(1, 2)

In [30]:
c = np.concatenate([a, b]) # defaults at a row level
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
c.shape

(3, 2)

In [32]:
np.concatenate([a, b], axis = 0) # 0 means row level and 1 means col level

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
a.shape

(2, 2)

In [34]:
b.shape

(1, 2)

In [36]:
b

array([[5, 6]])

In [37]:
d = b.T # T for Transpose - Switching cols into rows and vice versa
d

array([[5],
       [6]])

In [38]:
d.shape

(2, 1)

In [40]:
e = np.concatenate([a, b.T], axis = 1)
e

array([[1, 2, 5],
       [3, 4, 6]])

In [41]:
e.shape

(2, 3)

In [42]:
np.vstack([a, b]) # equal to np.concatenate([a, b], axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
np.hstack([a, b.T]) # equal to np.concatenate([a, b.T], axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [45]:
arr = np.random.randint(10, 100, (6, 4))
arr

array([[41, 60, 64, 74],
       [38, 98, 64, 81],
       [98, 76, 88, 20],
       [70, 55, 31, 45],
       [84, 26, 96, 54],
       [44, 99, 14, 41]])

In [48]:
np.vsplit(arr, 6) #splitting it into rows

[array([[41, 60, 64, 74]]),
 array([[38, 98, 64, 81]]),
 array([[98, 76, 88, 20]]),
 array([[70, 55, 31, 45]]),
 array([[84, 26, 96, 54]]),
 array([[44, 99, 14, 41]])]

In [49]:
np.vsplit(arr, 6)[3]

array([[70, 55, 31, 45]])

In [50]:
np.vsplit(arr, 3)

[array([[41, 60, 64, 74],
        [38, 98, 64, 81]]),
 array([[98, 76, 88, 20],
        [70, 55, 31, 45]]),
 array([[84, 26, 96, 54],
        [44, 99, 14, 41]])]

In [51]:
np.vsplit(arr, 2)

[array([[41, 60, 64, 74],
        [38, 98, 64, 81],
        [98, 76, 88, 20]]),
 array([[70, 55, 31, 45],
        [84, 26, 96, 54],
        [44, 99, 14, 41]])]

In [53]:
np.vsplit(arr, 4)

ValueError: array split does not result in an equal division

In [54]:
arr

array([[41, 60, 64, 74],
       [38, 98, 64, 81],
       [98, 76, 88, 20],
       [70, 55, 31, 45],
       [84, 26, 96, 54],
       [44, 99, 14, 41]])

In [55]:
np.hsplit(arr, 4)

[array([[41],
        [38],
        [98],
        [70],
        [84],
        [44]]),
 array([[60],
        [98],
        [76],
        [55],
        [26],
        [99]]),
 array([[64],
        [64],
        [88],
        [31],
        [96],
        [14]]),
 array([[74],
        [81],
        [20],
        [45],
        [54],
        [41]])]

In [56]:
np.hsplit(arr, 2)

[array([[41, 60],
        [38, 98],
        [98, 76],
        [70, 55],
        [84, 26],
        [44, 99]]),
 array([[64, 74],
        [64, 81],
        [88, 20],
        [31, 45],
        [96, 54],
        [14, 41]])]

# Matrix Multiplication

In [57]:
arr1

array([[86, 95, 12, 49, 87],
       [79, 51, 13, 63, 82],
       [37, 45, 70, 35, 13]])

In [58]:
arr2

array([[22, 54, 20, 64, 57],
       [52, 25, 42, 51, 91],
       [62, 28, 47, 26, 71]])

In [59]:
arr1 + arr2

array([[108, 149,  32, 113, 144],
       [131,  76,  55, 114, 173],
       [ 99,  73, 117,  61,  84]])

In [60]:
arr1 - arr2

array([[ 64,  41,  -8, -15,  30],
       [ 27,  26, -29,  12,  -9],
       [-25,  17,  23,   9, -58]])

In [61]:
arr1 * arr2

array([[1892, 5130,  240, 3136, 4959],
       [4108, 1275,  546, 3213, 7462],
       [2294, 1260, 3290,  910,  923]])

In [62]:
m1 = np.matrix([[1,2,3], [4,5,6]])
m1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [63]:
m1.shape

(2, 3)

In [64]:
m2 = np.matrix([[7,8,9], [10, 11, 12]])
m2

matrix([[ 7,  8,  9],
        [10, 11, 12]])

In [65]:
m1 + m2

matrix([[ 8, 10, 12],
        [14, 16, 18]])

In [66]:
m1 - m2

matrix([[-6, -6, -6],
        [-6, -6, -6]])

In [67]:
m1 * m2

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [68]:
m1.shape

(2, 3)

In [69]:
m2.shape

(2, 3)

In [70]:
m2 = m2.T
m2

matrix([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [71]:
m2.shape

(3, 2)

In [73]:
m1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [74]:
m2

matrix([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [72]:
m1 * m2

matrix([[ 50,  68],
        [122, 167]])

In [75]:
m1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [76]:
a1 = np.array(m1)
a1

array([[1, 2, 3],
       [4, 5, 6]])

# Pandas

In [2]:
import pandas as pd
import random # for generating random numerical values
import names # for generating random names !pip install names

In [3]:
# Object - Text
# Int/Float - Numerical
# Datetime - Date

In [4]:
s = pd.Series([1,1.2, True, 'Python'])
s

0         1
1       1.2
2      True
3    Python
dtype: object

In [5]:
s[3]

'Python'

In [6]:
s[2]

True

In [7]:
l = [1,2,3.2, 'Python', False]
l

[1, 2, 3.2, 'Python', False]

In [8]:
pd.Series(l)

0         1
1         2
2       3.2
3    Python
4     False
dtype: object

In [83]:
s

0         1
1       1.2
2      True
3    Python
dtype: object

In [9]:
s[3]

'Python'

In [12]:
list("ABCD")

['A', 'B', 'C', 'D']

In [86]:
s = pd.Series([1,1.2, True, 'Python'], index = list("ABCD"))
s

A         1
B       1.2
C      True
D    Python
dtype: object

In [87]:
s['D']

'Python'

In [88]:
s['C']

True

In [ ]:
# One-dimesional outputs will always be treated as Series and 2d will be DataFrames

In [13]:
np.random.randint(10, 1000, [10, 4])

array([[332,  35, 640, 291],
       [360, 410, 251, 721],
       [668, 151, 565, 413],
       [513, 550,  19, 370],
       [607,  90, 264, 788],
       [548, 106, 627, 266],
       [627,  27, 422, 619],
       [688, 720, 469, 671],
       [118, 241, 313, 552],
       [768, 728,  94, 911]])

In [14]:
df = pd.DataFrame(np.random.randint(10, 1000, [10, 4]))
df

0    1    2    3
0  599  742  417  390
1  306  373  214  692
2  807  754   24  400
3  681  332  162   31
4  883  918  948  686
5  579  854  201  369
6  597  667  671  463
7  925  289  931   34
8  376  786  230  280
9  462  903  296  736

In [15]:
df = pd.DataFrame(np.random.randint(10, 1000, [10, 4]), columns = ['Apple', 'MS', 'Netflix', 'Amazon'])
df

Apple   MS  Netflix  Amazon
0    808  625      505     157
1    266  440      465     807
2    257  944      436     970
3    517  337      680     393
4    969  627      683     442
5    483  350      282     237
6     62  145      976     533
7    803  667      578     864
8    998  337      780     987
9    178   14      207     536

In [16]:
df = pd.DataFrame(np.random.randint(10, 1000, [10, 4]), 
                  index = list("ABCDEFGHIJ"),
                  columns = ['Apple', 'MS', 'Netflix', 'Amazon'])
df

Apple   MS  Netflix  Amazon
A    935  515      135     779
B    373  320      379     361
C    439  171      742     658
D    130   61      184     129
E     54  248      217     269
F    586  894      400     824
G    606  186      565     929
H     38  329      708     255
I    244  865      470     649
J    265  851      907     370

In [17]:
df['A']

KeyError: 'A'

In [18]:
df['Apple'] # Series

A    935
B    373
C    439
D    130
E     54
F    586
G    606
H     38
I    244
J    265
Name: Apple, dtype: int32

In [19]:
df[['Apple', 'MS']] # Series

Apple   MS
A    935  515
B    373  320
C    439  171
D    130   61
E     54  248
F    586  894
G    606  186
H     38  329
I    244  865
J    265  851

In [20]:
name = [names.get_first_name() for i in range(10)]
maths = [random.randint(35, 100) for i in range(10)]
physics = [random.randint(35, 100) for i in range(10)]

In [21]:
print(name, end = " ")

['Estella', 'Christopher', 'Sandra', 'Lori', 'Samuel', 'Christine', 'Ruby', 'Louis', 'Barbara', 'Carol'] 

In [22]:
print(maths, end = " ")

[64, 62, 44, 57, 71, 59, 53, 89, 76, 55] 

In [23]:
print(physics, end = " ")

[42, 93, 45, 92, 100, 55, 75, 62, 56, 91] 

In [24]:
students = pd.DataFrame({"Name" : name, "Maths" : maths, "Physics" : physics})
students

Name  Maths  Physics
0      Estella     64       42
1  Christopher     62       93
2       Sandra     44       45
3         Lori     57       92
4       Samuel     71      100
5    Christine     59       55
6         Ruby     53       75
7        Louis     89       62
8      Barbara     76       56
9        Carol     55       91

# Accessing values from DF

In [25]:
students

Name  Maths  Physics
0      Estella     64       42
1  Christopher     62       93
2       Sandra     44       45
3         Lori     57       92
4       Samuel     71      100
5    Christine     59       55
6         Ruby     53       75
7        Louis     89       62
8      Barbara     76       56
9        Carol     55       91

In [28]:
students['Name']

0        Estella
1    Christopher
2         Sandra
3           Lori
4         Samuel
5      Christine
6           Ruby
7          Louis
8        Barbara
9          Carol
Name: Name, dtype: object

In [29]:
students.Name

0        Estella
1    Christopher
2         Sandra
3           Lori
4         Samuel
5      Christine
6           Ruby
7          Louis
8        Barbara
9          Carol
Name: Name, dtype: object

# Indexing - Slicing & Dicing
* iloc - Index location
    1. Excludes the last position
    1. Access the values based on its position
    
* loc - Location Function
    1. Includes the end value
    1. Access the values based on its representation (col header, index value)

In [30]:
students.iloc[:, :] # row indexing, col indexing

Name  Maths  Physics
0      Estella     64       42
1  Christopher     62       93
2       Sandra     44       45
3         Lori     57       92
4       Samuel     71      100
5    Christine     59       55
6         Ruby     53       75
7        Louis     89       62
8      Barbara     76       56
9        Carol     55       91

In [31]:
students.iloc[4:8, :2] # row indexing, col indexing

Name  Maths
4     Samuel     71
5  Christine     59
6       Ruby     53
7      Louis     89

In [32]:
students.iloc[[1,3,5,7], :] # row indexing, col indexing

Name  Maths  Physics
1  Christopher     62       93
3         Lori     57       92
5    Christine     59       55
7        Louis     89       62

In [33]:
students.iloc[:, [0, 2]] # row indexing, col indexing

Name  Physics
0      Estella       42
1  Christopher       93
2       Sandra       45
3         Lori       92
4       Samuel      100
5    Christine       55
6         Ruby       75
7        Louis       62
8      Barbara       56
9        Carol       91

In [34]:
students

Name  Maths  Physics
0      Estella     64       42
1  Christopher     62       93
2       Sandra     44       45
3         Lori     57       92
4       Samuel     71      100
5    Christine     59       55
6         Ruby     53       75
7        Louis     89       62
8      Barbara     76       56
9        Carol     55       91

In [35]:
students.loc[:, :] # row indexing - Value, col indexing - value

Name  Maths  Physics
0      Estella     64       42
1  Christopher     62       93
2       Sandra     44       45
3         Lori     57       92
4       Samuel     71      100
5    Christine     59       55
6         Ruby     53       75
7        Louis     89       62
8      Barbara     76       56
9        Carol     55       91

In [36]:
students.loc[0:5, 'Name':'Maths']

Name  Maths
0      Estella     64
1  Christopher     62
2       Sandra     44
3         Lori     57
4       Samuel     71
5    Christine     59

In [37]:
students.loc[[0,2,5], ['Name','Physics']]

Name  Physics
0    Estella       42
2     Sandra       45
5  Christine       55

In [38]:
students.index = list("ABCDEFGHIJ")
students

Name  Maths  Physics
A      Estella     64       42
B  Christopher     62       93
C       Sandra     44       45
D         Lori     57       92
E       Samuel     71      100
F    Christine     59       55
G         Ruby     53       75
H        Louis     89       62
I      Barbara     76       56
J        Carol     55       91

In [39]:
students.loc['A':"F", :]

Name  Maths  Physics
A      Estella     64       42
B  Christopher     62       93
C       Sandra     44       45
D         Lori     57       92
E       Samuel     71      100
F    Christine     59       55

In [123]:
students.loc[1:6, :]

TypeError: cannot do slice indexing on Index with these indexers [1] of type int

In [40]:
students.loc['A':"F", :]

Name  Maths  Physics
A      Estella     64       42
B  Christopher     62       93
C       Sandra     44       45
D         Lori     57       92
E       Samuel     71      100
F    Christine     59       55

In [41]:
students.iloc[-2:, :]

Name  Maths  Physics
I  Barbara     76       56
J    Carol     55       91

In [42]:
d = {"A" : "Python", "B" : "Java", "C" : "C++"}
d

{'A': 'Python', 'B': 'Java', 'C': 'C++'}

In [43]:
pd.Series(d.values(), index = d.keys())

A    Python
B      Java
C       C++
dtype: object

# Files Handling

In [44]:
pwd #prints your current working directory

'C:\\Users\\harshal gidh\\Desktop\\Python'

In [45]:
import os #operating system

In [46]:
os.getcwd() #Gets your current working Directory

'C:\\Users\\harshal gidh\\Desktop\\Python'

In [47]:
os.listdir() #lists all the files in the cwd

['.ipynb_checkpoints',
 '10 dec python.ipynb',
 '17 December Data science - Jupyter Notebook.pdf',
 '363.frontend.py',
 '364.backend.py',
 '4 dec Data science - Jupyter Notebook.pdf',
 '4 dec Data science.ipynb',
 'backend1.py',
 'C programs',
 'Day 1 - NumPy(1)',
 'Day 1 - NumPy(2)',
 'Day 1 - NumPy(3).ipynb',
 'Day 1 - NumPy(4).ipynb',
 'Day 1 - NumPy.ipynb',
 'Day 2 - NumPy & Pandas(1).ipynb',
 'Day 2 - NumPy & Pandas(2).ipynb',
 'Day 2 - NumPy & Pandas.ipymb',
 'distance_M1_PRAC_A413.py',
 'Duplicates.xlsx',
 'exp1.py',
 'exp10.py',
 'exp11.py',
 'exp12.py',
 'exp2.py',
 'exp3.py',
 'exp4.py',
 'exp5.py',
 'exp6.py',
 'exp7.py',
 'exp8.py',
 'exp9.py',
 'FizzBuzz.py',
 'Frontend.py',
 'hello world.py',
 'IDLE (Python 3.8 32-bit).lnk',
 'Linear Algebra - Python.pdf',
 'Markdown_Features.ipynb',
 'Matplotlib.pdf',
 'Module 1 - File 1.pdf',
 'new.txt',
 'newfile.txt',
 'Numpy Exercises.pdf',
 'oops concepts 2 - Jupyter Notebook.pdf',
 'oops handson - Jupyter Notebook.pdf',
 "P'COM Man

In [48]:
# To read data from current path - xlsx, csv
sales1 = pd.read_excel("Sales.xlsx")
sales1.shape

(5000, 11)

In [50]:
sales1.head(2)

OrderID  OrderDate  PropertyID  ProductID  Quantity   ProductName  \
0        1 2015-01-01          17         41         1  Office Chair   
1      163        NaT          17         41         2  Office Chair   

  ProductCategory  Price PropertyCity PropertyState  sales  
0     Furnishings     85    Las Vegas        Nevada     85  
1     Furnishings     85    Las Vegas        Nevada    170

In [137]:
# To read data from current path - xlsx, csv
sales1 = pd.read_csv("C:\Users\dukef\OneDrive\Documents\Teaching\Intellipaat\Weekend\Aug'22 Batch\Sales.csv")
sales1.shape

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (924253148.py, line 2)

In [51]:
# r - Raw Literal String

In [ ]:
pd.read # press TAB to auto-complete list

In [54]:
# To read data from current path - xlsx, csv
sales2 = pd.read_csv(r"C:\Users\harshal gidh\Desktop\Python\Sales.csv")
sales2.shape

(5000, 11)

In [55]:
sales2.head(2)

OrderID   OrderDate  PropertyID  ProductID  Quantity   ProductName  \
0        1  01-01-2015          17         41         1  Office Chair   
1      163         NaN          17         41         2  Office Chair   

  ProductCategory  Price PropertyCity PropertyState  sales  
0     Furnishings     85    Las Vegas        Nevada     85  
1     Furnishings     85    Las Vegas        Nevada    170

In [ ]:
# os.chdir(r"C:\Users\dukef\OneDrive\Documents\Teaching\Intellipaat\Weekend\Aug'22 Batch")

In [56]:
test = pd.read_excel("PropertyOrderProduct.xlsx") #reads the first sheet by default
test.head(2)

PropertyID PropertyCity PropertyState
0           1     New York      New York
1           2   Cincinnati          Ohio

In [57]:
test2 = pd.read_excel("PropertyOrderProduct.xlsx", sheet_name = "Products")
test2.head(2)

ProductID  ProductName ProductCategory  Price
0          1  Large Towel    Housekeeping      9
1          2   Hand Towel    Housekeeping      5

In [58]:
alldf = pd.read_excel("PropertyOrderProduct.xlsx", sheet_name = None) #reads all the sheets as dict
alldf.keys() #keys are the sheet name and values are the tables

dict_keys(['PropertyInfo', 'Products', 'OrderDetails'])

In [59]:
props = alldf['PropertyInfo'] 
prods = alldf['Products'] 
ords = alldf['OrderDetails'] 

In [60]:
props.head(2)

PropertyID PropertyCity PropertyState
0           1     New York      New York
1           2   Cincinnati          Ohio

In [61]:
prods.head(2)

ProductID  ProductName ProductCategory  Price
0          1  Large Towel    Housekeeping      9
1          2   Hand Towel    Housekeeping      5

In [62]:
ords.head(2)

OrderID  OrderDate  PropertyID  ProductID  Quantity
0        1 2015-01-01          17         41         1
1        2 2015-01-01          15         54         2

In [ ]:
# pyodbc, sqlite3, mysql2 or mysql3

In [151]:
nr = pd.read_excel("PropertyOrderProduct.xlsx", sheet_name = 'NewTable') 
nr.head(2)

ValueError: Worksheet named 'NewTable' not found

# Writing Data

In [63]:
students.to_csv("Students.csv", index = False)
students.to_excel("Students.xlsx", index = False)

# Operations in Pandas

* Files Handling - Read and Write
* Basic Functions - Table metadata
* Sorting index and values
* Boolean Indexing
* Handling Columns
* Handling Rows
* Handling Duplicates
* Handling Missing Values
* Group by & Pivot table
* Merge & Joins
* Concat & append, Stacking
* Melt

# Basic Functions - Table metadata

In [64]:
df = sales2.copy()

In [65]:
df.columns

Index(['OrderID', 'OrderDate', 'PropertyID', 'ProductID', 'Quantity',
       'ProductName', 'ProductCategory', 'Price', 'PropertyCity',
       'PropertyState', 'sales'],
      dtype='object')

In [66]:
df.index

RangeIndex(start=0, stop=5000, step=1)

In [67]:
df.dtypes # data type of every single col

OrderID             int64
OrderDate          object
PropertyID          int64
ProductID           int64
Quantity            int64
ProductName        object
ProductCategory    object
Price               int64
PropertyCity       object
PropertyState      object
sales               int64
dtype: object

In [68]:
df.info() #metadata of the table

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   OrderID          5000 non-null   int64 
 1   OrderDate        4978 non-null   object
 2   PropertyID       5000 non-null   int64 
 3   ProductID        5000 non-null   int64 
 4   Quantity         5000 non-null   int64 
 5   ProductName      5000 non-null   object
 6   ProductCategory  5000 non-null   object
 7   Price            5000 non-null   int64 
 8   PropertyCity     5000 non-null   object
 9   PropertyState    5000 non-null   object
 10  sales            5000 non-null   int64 
dtypes: int64(6), object(5)
memory usage: 429.8+ KB


In [69]:
df.head() #previews the first 5 rows

OrderID   OrderDate  PropertyID  ProductID  Quantity       ProductName  \
0        1  01-01-2015          17         41         1      Office Chair   
1      163         NaN          17         41         2      Office Chair   
2     1598         NaN          17         41         3      Office Chair   
3     4155         NaN          17         41         2      Office Chair   
4     1109         NaN          17         54         2  Chest of Drawers   

  ProductCategory  Price PropertyCity PropertyState  sales  
0     Furnishings     85    Las Vegas        Nevada     85  
1     Furnishings     85    Las Vegas        Nevada    170  
2     Furnishings     85    Las Vegas        Nevada    255  
3     Furnishings     85    Las Vegas        Nevada    170  
4     Furnishings    150    Las Vegas        Nevada    300

In [70]:
df.head(2) #first two rows

OrderID   OrderDate  PropertyID  ProductID  Quantity   ProductName  \
0        1  01-01-2015          17         41         1  Office Chair   
1      163         NaN          17         41         2  Office Chair   

  ProductCategory  Price PropertyCity PropertyState  sales  
0     Furnishings     85    Las Vegas        Nevada     85  
1     Furnishings     85    Las Vegas        Nevada    170

In [71]:
df.tail() # last 5 records

OrderID   OrderDate  PropertyID  ProductID  Quantity  \
4995     4347  16-09-2016          10         43         1   
4996     4275  06-09-2016          10         76         3   
4997      765  26-04-2015          10         26         1   
4998     1034  03-06-2015          10         26         2   
4999     4990  30-12-2016          10         32         1   

              ProductName  ProductCategory  Price PropertyCity PropertyState  \
4995           Table Lamp      Furnishings     38    Arlington      Virginia   
4996                Ficus     Public Areas     80    Arlington      Virginia   
4997  Envelopes (Catalog)  Office Supplies     13    Arlington      Virginia   
4998  Envelopes (Catalog)  Office Supplies     13    Arlington      Virginia   
4999            Note Pads  Office Supplies     14    Arlington      Virginia   

      sales  
4995     38  
4996    240  
4997     13  
4998     26  
4999     14

In [72]:
df.tail(2)

OrderID   OrderDate  PropertyID  ProductID  Quantity  \
4998     1034  03-06-2015          10         26         2   
4999     4990  30-12-2016          10         32         1   

              ProductName  ProductCategory  Price PropertyCity PropertyState  \
4998  Envelopes (Catalog)  Office Supplies     13    Arlington      Virginia   
4999            Note Pads  Office Supplies     14    Arlington      Virginia   

      sales  
4998     26  
4999     14

In [73]:
df.shape

(5000, 11)

In [74]:
df.nunique() #Number of unique values in each & every col

OrderID            5000
OrderDate           731
PropertyID           20
ProductID            94
Quantity              3
ProductName          94
ProductCategory       5
Price                48
PropertyCity         20
PropertyState        18
sales               112
dtype: int64

In [75]:
df['ProductCategory'].unique()

array(['Furnishings', 'Maintenance', 'Housekeeping', 'Public Areas',
       'Office Supplies'], dtype=object)

In [76]:
# Frequency Distribution
df.value_counts('ProductCategory') 

ProductCategory
Furnishings        1368
Public Areas       1101
Housekeeping       1063
Maintenance         804
Office Supplies     664
dtype: int64

# Agg for all numerical col

In [77]:
df.describe() # basic agg for all numerical cols

OrderID   PropertyID    ProductID     Quantity        Price  \
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000   
mean   2500.500000    10.541400    47.162600     2.019200    52.919000   
std    1443.520003     5.719478    27.355004     0.811519    57.552297   
min       1.000000     1.000000     1.000000     1.000000     3.000000   
25%    1250.750000     6.000000    23.000000     1.000000    17.000000   
50%    2500.500000    11.000000    47.000000     2.000000    30.000000   
75%    3750.250000    15.000000    70.000000     3.000000    75.000000   
max    5000.000000    20.000000    94.000000     3.000000   300.000000   

             sales  
count  5000.000000  
mean    106.695800  
std     131.575007  
min       3.000000  
25%      27.000000  
50%      60.000000  
75%     120.000000  
max     900.000000

In [78]:
df['sales'].describe()

count    5000.000000
mean      106.695800
std       131.575007
min         3.000000
25%        27.000000
50%        60.000000
75%       120.000000
max       900.000000
Name: sales, dtype: float64

# Sorting index and values

In [79]:
students

Name  Maths  Physics
A      Estella     64       42
B  Christopher     62       93
C       Sandra     44       45
D         Lori     57       92
E       Samuel     71      100
F    Christine     59       55
G         Ruby     53       75
H        Louis     89       62
I      Barbara     76       56
J        Carol     55       91

In [84]:
dates = pd.date_range(start = "2022-12-31", periods = 10, freq = "d") #yyyy-mm-dd # 10 days
dates

DatetimeIndex(['2022-12-31', '2023-01-01', '2023-01-02', '2023-01-03',
               '2023-01-04', '2023-01-05', '2023-01-06', '2023-01-07',
               '2023-01-08', '2023-01-09'],
              dtype='datetime64[ns]', freq='D')

In [85]:
students['Date'] = dates
students

Name  Maths  Physics       Date
A      Estella     64       42 2022-12-31
B  Christopher     62       93 2023-01-01
C       Sandra     44       45 2023-01-02
D         Lori     57       92 2023-01-03
E       Samuel     71      100 2023-01-04
F    Christine     59       55 2023-01-05
G         Ruby     53       75 2023-01-06
H        Louis     89       62 2023-01-07
I      Barbara     76       56 2023-01-08
J        Carol     55       91 2023-01-09

In [86]:
students.sort_index() #Sorts the index in asc order

Name  Maths  Physics       Date
A      Estella     64       42 2022-12-31
B  Christopher     62       93 2023-01-01
C       Sandra     44       45 2023-01-02
D         Lori     57       92 2023-01-03
E       Samuel     71      100 2023-01-04
F    Christine     59       55 2023-01-05
G         Ruby     53       75 2023-01-06
H        Louis     89       62 2023-01-07
I      Barbara     76       56 2023-01-08
J        Carol     55       91 2023-01-09

In [87]:
students.sort_index(ascending = False)

Name  Maths  Physics       Date
J        Carol     55       91 2023-01-09
I      Barbara     76       56 2023-01-08
H        Louis     89       62 2023-01-07
G         Ruby     53       75 2023-01-06
F    Christine     59       55 2023-01-05
E       Samuel     71      100 2023-01-04
D         Lori     57       92 2023-01-03
C       Sandra     44       45 2023-01-02
B  Christopher     62       93 2023-01-01
A      Estella     64       42 2022-12-31

In [88]:
students.sort_values(by = "Name") #Defaults in asc order

Name  Maths  Physics       Date
I      Barbara     76       56 2023-01-08
J        Carol     55       91 2023-01-09
F    Christine     59       55 2023-01-05
B  Christopher     62       93 2023-01-01
A      Estella     64       42 2022-12-31
D         Lori     57       92 2023-01-03
H        Louis     89       62 2023-01-07
G         Ruby     53       75 2023-01-06
E       Samuel     71      100 2023-01-04
C       Sandra     44       45 2023-01-02

In [89]:
students.sort_values(by = "Name", ascending = False)

Name  Maths  Physics       Date
C       Sandra     44       45 2023-01-02
E       Samuel     71      100 2023-01-04
G         Ruby     53       75 2023-01-06
H        Louis     89       62 2023-01-07
D         Lori     57       92 2023-01-03
A      Estella     64       42 2022-12-31
B  Christopher     62       93 2023-01-01
F    Christine     59       55 2023-01-05
J        Carol     55       91 2023-01-09
I      Barbara     76       56 2023-01-08

In [90]:
students.sort_values(by = "Maths", ascending = False)

Name  Maths  Physics       Date
H        Louis     89       62 2023-01-07
I      Barbara     76       56 2023-01-08
E       Samuel     71      100 2023-01-04
A      Estella     64       42 2022-12-31
B  Christopher     62       93 2023-01-01
F    Christine     59       55 2023-01-05
D         Lori     57       92 2023-01-03
J        Carol     55       91 2023-01-09
G         Ruby     53       75 2023-01-06
C       Sandra     44       45 2023-01-02

In [91]:
students.sort_values(by = "Date", ascending = False)

Name  Maths  Physics       Date
J        Carol     55       91 2023-01-09
I      Barbara     76       56 2023-01-08
H        Louis     89       62 2023-01-07
G         Ruby     53       75 2023-01-06
F    Christine     59       55 2023-01-05
E       Samuel     71      100 2023-01-04
D         Lori     57       92 2023-01-03
C       Sandra     44       45 2023-01-02
B  Christopher     62       93 2023-01-01
A      Estella     64       42 2022-12-31

In [92]:
students

Name  Maths  Physics       Date
A      Estella     64       42 2022-12-31
B  Christopher     62       93 2023-01-01
C       Sandra     44       45 2023-01-02
D         Lori     57       92 2023-01-03
E       Samuel     71      100 2023-01-04
F    Christine     59       55 2023-01-05
G         Ruby     53       75 2023-01-06
H        Louis     89       62 2023-01-07
I      Barbara     76       56 2023-01-08
J        Carol     55       91 2023-01-09

In [93]:
# Boolean Indexing
# Handling Columns
# Handling Rows

In [94]:
test = pd.DataFrame({"Col1" : ["A", "A", "B", "A", "B"], "Col2" : [11,9,45, 15, 7]})
test

Col1  Col2
0    A    11
1    A     9
2    B    45
3    A    15
4    B     7

In [95]:
test.sort_values(by = "Col1")

Col1  Col2
0    A    11
1    A     9
3    A    15
2    B    45
4    B     7

In [96]:
test.sort_values(by = ["Col1", "Col2"], ascending = False)

Col1  Col2
2    B    45
4    B     7
3    A    15
0    A    11
1    A     9

# Boolean Indexing

In [97]:
students

Name  Maths  Physics       Date
A      Estella     64       42 2022-12-31
B  Christopher     62       93 2023-01-01
C       Sandra     44       45 2023-01-02
D         Lori     57       92 2023-01-03
E       Samuel     71      100 2023-01-04
F    Christine     59       55 2023-01-05
G         Ruby     53       75 2023-01-06
H        Louis     89       62 2023-01-07
I      Barbara     76       56 2023-01-08
J        Carol     55       91 2023-01-09

In [98]:
students[students['Maths'] > 50]

Name  Maths  Physics       Date
A      Estella     64       42 2022-12-31
B  Christopher     62       93 2023-01-01
D         Lori     57       92 2023-01-03
E       Samuel     71      100 2023-01-04
F    Christine     59       55 2023-01-05
G         Ruby     53       75 2023-01-06
H        Louis     89       62 2023-01-07
I      Barbara     76       56 2023-01-08
J        Carol     55       91 2023-01-09

In [99]:
students[(students['Maths'] > 50) & (students['Physics'] > 50)]

Name  Maths  Physics       Date
B  Christopher     62       93 2023-01-01
D         Lori     57       92 2023-01-03
E       Samuel     71      100 2023-01-04
F    Christine     59       55 2023-01-05
G         Ruby     53       75 2023-01-06
H        Louis     89       62 2023-01-07
I      Barbara     76       56 2023-01-08
J        Carol     55       91 2023-01-09

In [100]:
students[(students['Maths'] > 50) & (students['Physics'] > 50)]['Name']

B    Christopher
D           Lori
E         Samuel
F      Christine
G           Ruby
H          Louis
I        Barbara
J          Carol
Name: Name, dtype: object

In [101]:
students[(students['Maths'] > 50) & (students['Physics'] > 50)][['Name', 'Maths', 'Physics']]

Name  Maths  Physics
B  Christopher     62       93
D         Lori     57       92
E       Samuel     71      100
F    Christine     59       55
G         Ruby     53       75
H        Louis     89       62
I      Barbara     76       56
J        Carol     55       91

In [102]:
len(students[(students['Maths'] > 50) & (students['Physics'] > 50)])

8

In [103]:
students[(students['Maths'] > 50) & (students['Physics'] > 50)]['Name'].shape[0]

8

# Handling Columns 
# Handling Rows